[package]
name = "z85"
version = "0.1.1"
authors = ["Mehmet Kose"]
description = "ZeroMQ's base85 algorithm"
license = "MIT/Apache-2.0"
repository = "https://github.com/decafbad/z85-rust"

[dev-dependencies]
quickcheck = "0.2.18"
